data:
  start: "2024-04-16"
  end: "2024-04-30"
  grid:
    lats:
      start: 36.0
      stop: 44.0
      step: 0.25
    lons:
      start: -10.0
      stop: 4.0
      step: 0.25
model:
  max_encoder_length: 24
  max_prediction_length: 1
  batch_size: 128
  max_epochs: 1
  targets: ["wind_speed", "wind_dir_sin", "wind_dir_cos"]
  static_reals: ["latitude", "longitude", "elevacion_m"]
  time_varying_known_reals : ["time_idx"]
  time_varying_unknown_reals : ["wind_speed", "wind_dir_sin", "wind_dir_cos", "u10", "v10", "u100", "v100","t2m", "d2m", "skt", "sp", "msl", "tp", "ssrd", "strd"]